# Generated by Django 4.2 on 2026-05-18 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок питання')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL (Slug)')),
                ('content', models.TextField(verbose_name='Детальний опис проблеми')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опубліковано'), ('closed', 'Закрито')], default='published', max_length=10, verbose_name='Статус')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
                'ordering': ['-created_at'],
            },
        ),
    ]
